### PR TITLE
Fix the import for frontend

### PR DESCRIPTION
**Pull request by manjeetbhatia**
The frontend import will give an error if
this is installed using python3 setup.py install.
The init module is added to make it easily importable.

### CODE REVIEW

**Comment by cooperlees** [comment]
What's the error you see without this diff? I didn't think this was required with Python 3. Also, what version of Python 3 did you test this in?

**Comment by manjeetbhatia** [comment]
python 3.6.8

Error trace:
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/memory_analyzer-0.1.1-py3.6.egg/memory_analyzer/memory_analyzer.py", line 18, in <module>
    from .frontend import frontend_utils
ModuleNotFoundError: No module named 'frontend'

**Comment by thatch** [comment]
Yes, this is valid.  I have more tests coming to catch this sort of thing.

**Comment by lisroach** [comment]
@thatch do you mind if I merge this one first and you rebase your PR?

**Comment by thatch** [comment]
When you gave the LG I went ahead and merged the other one, so these changes are already handled (with copyright notice)

**Pull request merged**
